### ISSUE TITLE
Unexpected exception when package version does not follow semver

### ISSUE THREAD

**Issue by ad-ops** [stevedesmond-ca/dotnet-libyear#24]
#### Problem
Having a reference that uses an [incorrect](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) semver version like this:

```
<ItemGroup Condition="'$(os)' == 'Windows_NT'">
	<PackageReference Include="IBM.Data.DB2.Core" Version="1.3.0.100" />
</ItemGroup>

<ItemGroup Condition="'$(os)' == 'Unix'">
	<PackageReference Include="IBM.Data.DB2.Core-lnx" Version="1.3.0.100" />
</ItemGroup>
```

Gives the following error:
```
Sorry, an unexpected exception has occurred: System.ArgumentException: '1.3.0.100' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.SemanticVersion.Parse(String value)
   at LibYear.Lib.FileTypes.XmlProjectFile.<>c__DisplayClass10_0.<.ctor>b__1(XElement d) in X:\LibYear\src\LibYear.Lib\FileTypes\XmlProjectFile.cs:line 31
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at LibYear.Lib.FileTypes.XmlProjectFile..ctor(String filename, String elementName, String[] packageAttributeNames, String versionAttributeName) in X:\LibYear\src\LibYear.Lib\FileTypes\XmlProjectFile.cs:line 29
   at LibYear.Lib.FileTypes.CsProjFile..ctor(String filename) in X:\LibYear\src\LibYear.Lib\FileTypes\CsProjFile.cs:line 7
   at LibYear.Lib.FileUtils.ToProjectFile(String path) in X:\LibYear\src\LibYear.Lib\FileUtils.cs:line 18
   at LibYear.Lib.ProjectFileManager.GetProjects(String arg) in X:\LibYear\src\LibYear.Lib\ProjectFileManager.cs:line 17
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LibYear.Lib.ProjectFileManager.GetAllProjects(IReadOnlyList`1 args) in X:\LibYear\src\LibYear.Lib\ProjectFileManager.cs:line 11
   at LibYear.App.Runner.Run(List`1 args) in X:\LibYear\src\LibYear\Runner.cs:line 41
   at LibYear.App.Program.Main(String[] args) in X:\LibYear\src\LibYear\Program.cs:line 24
```

#### Expected behavior
Swallow the exception and to display the libyear if it is an accepted Nuget package and perhaps with an error message. 

Alternatively using a flag when running the program to use a non-strict version checking and/or suppressing errors in individual packages.

**Comment by mbielski** [comment]
I get this message too and came to the same conclusions. Semver is nice, but not everything follows it.

**Comment by stevedesmond-ca** [comment]
Thanks for reporting! This was fixed in #20 for #17, I just haven't gotten around to releasing a new version yet, but you can build it yourself to get the fix until then.

**Comment by mdschweda** [comment]
Any chance for a release in the foreseeable future?

**Comment by stevedesmond-ca** [comment]
@mdschweda v4.1.0 has been released, thanks for the bump!
