### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by fubar-coder** [stevedesmond-ca/dotnet-libyear#3]
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LibYear.FileTypes.XmlProjectFile.<.ctor>b__10_0(XElement d)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at LibYear.FileTypes.XmlProjectFile..ctor(String filename, String elementName, String packageAttributeName, String versionAttributeName)
   at LibYear.ProjectFileManager.GetAllProjects(IReadOnlyList`1 args)
   at LibYear.Runner.Run(IReadOnlyList`1 args)
   at LibYear.Program.Main(String[] args)
```

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;net451</TargetFrameworks>
    <CodeAnalysisRuleSet>$(ProjectDir)..\..\WebDavServer.ruleset</CodeAnalysisRuleSet>
    <DocumentationFile Condition=" '$(Configuration)' == 'Release' ">bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <Version>0.1.0</Version>
    <Authors>Mark Junker</Authors>
    <Company>Fubar Development Junker</Company>
    <Product>WebDAV Server</Product>
    <Description>A .NET WebDAV server</Description>
    <Copyright>2016 © Fubar Development Junker</Copyright>
    <PackageLicenseUrl>https://github.com/FubarDevelopment/WebDavServer/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/FubarDevelopment/WebDavServer</PackageProjectUrl>
    <RepositoryUrl>https://github.com/FubarDevelopment/WebDavServer.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>0.1.0</AssemblyVersion>
    <FileVersion>0.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="NETStandard.Library" Version="1.6.1" />
    <PackageReference Include="JetBrains.Annotations" Version="10.4.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="1.1.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.Collections.Immutable" Version="1.3.1" />
    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
    <PackageReference Include="System.Interactive.Async" Version="3.1.1" />
    <PackageReference Include="System.Interactive.Async.Providers" Version="3.1.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.1" />
    <PackageReference Include="System.Security.Principal" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="$(ProjectDir)..\..\stylecop.json" Link="stylecop.json" />
    <EmbeddedResource Include="Utils\UAParser\UAParser.regexes.yaml" />
    <None Include="$(ProjectDir)..\..\WebDavServer.ruleset" Link="WebDavServer.ruleset" />
    <None Include="Model\webdav.xsd" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Model\webdav.cs">
      <DependentUpon>webdav.xsd</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Security.Claims">
      <Version>4.3.0</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="libyear" Version="*" />
  </ItemGroup>
</Project>
```

**Comment by stevedesmond-ca** [comment]
Looks like System.Security.Claims has a Version element instead of attribute. Quick fix is to make it a attribute, or feel free to submit a PR to handle sub-elements instead of attributes.

**Comment by stevedesmond-ca** [comment]
This will be in 1.0.2 later this week
