### ISSUE TITLE
Tool fails with directories with more than one project file

### ISSUE THREAD

**Issue by fubar-coder** [stevedesmond-ca/dotnet-libyear#4]
Due to docfx not supporting .NET core, I also have a `.projitems` and a `.shproj` file together with my `.csproj` file. Even though I specify the `csproj` file directly, I get the following exception:

```
Unhandled Exception: System.InvalidOperationException: Specify which project file to use because this 'C:\Users\fubar\Source\Repos\WebDavServer\src\FubarDev.WebDavServer' contains more than one project file.
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by stevedesmond-ca** [comment]
This is strictly in the​ realm of the .NET Core CLI (see the call stack) -- maybe it can't handle this case, or maybe you just need to make sure the project is after a specific flag.

**Comment by fubar-coder** [comment]
Please reopen this issue. Dotnet core works when I specify the csproj, so the problem really seems to be in your tool just passing the directory instead of the csproj.
